---
# tasks file for mysql
- name: Install Tools, Including MySql-Server
  apt: name={{item}} state=present update_cache=yes
  with_items: 
    - python-mysqldb
    - mysql-server
   
- name: ensure mysql linstening on all ports
  lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address 
              line="bind-address = {{ ansible_eth1.ipv4.address }}"    
#              line="bind-address = 0.0.0.0"
              
  notify: Restart MySql
      
- name: Create Database
  mysql_db: name={{ db_name }} state=present
   
- name: Create  User
  mysql_user: name={{ db_user_name}} password={{ db_user_pass}} 
              priv={{ db_name}}.*:ALL host='{{ db_user_host}}' state=present

- name: Ensure MySql Started
  service: name=mysql state=started enabled=yes