--- 
- hosts: database
  become: true
  tasks:
    - name: Install Tools, Including MySql-Server
      apt: name={{item}} state=present update_cache=yes
      with_items: 
        - python-mysqldb
        - mysql-server

    - name: Ensure MySql Started
      service: name=mysql state=started enabled=yes
      
    - name: ensure mysql linstening on all ports
      lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address 
                  line="bind-address = 0.0.0.0"
      notify: Restart MySql
      
    - name: Create Demo Database
      mysql_db: name=demo state=present
      
    - name: Create Demo User
      mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present

  handlers: 
    - name: Restart MySql
      service: name=mysql state=restarted
        